### ISSUE TITLE
Icons not working

### ISSUE THREAD

**Issue by kirbyfan64** [LightSnowDev/Material-Spring#1]
![screenshot from 2018-06-12 15-39-20](https://user-images.githubusercontent.com/1690697/41316043-d7b5424a-6e56-11e8-9822-c9ec2d6df9ba.png)

You can see the resources aren't being found, and the default icons are being used. :neutral_face:

**Comment by LightSnowDev** [comment]
Do the icons in the main menu work?
Can you check if the icons are present in the plugins' folder?
Can you check, if you have any images under "Sources"?
![image](https://user-images.githubusercontent.com/10366675/41814215-18ebac56-7747-11e8-9b87-5070811fa323.png)

**Comment by kirbyfan64** [comment]
![screenshot from 2018-06-24 16-23-45](https://user-images.githubusercontent.com/1690697/41823819-c68d7bf8-77cb-11e8-8be0-56d5819af7be.png)

(Blacked out the emails.)

Bizarrely enough, I see all the images in the *Sources* panel, but they're all the "broken image" icon:

![screenshot from 2018-06-24 16-34-07](https://user-images.githubusercontent.com/1690697/41823869-9d97a6aa-77cc-11e8-9584-ddaa909c2294.png)

**Comment by Myron-Biker** [comment]
I have the same problem, please fix this :). overall the theme looks nice!

**Comment by regulskimichal** [comment]
Change in package.json to the following:

> "name": "Material-Spring"

Linux filenames are case-sensitive.

**Comment by LightSnowDev** [comment]
>Linux filenames are case-sensitive.
Awsome! Did not know that.
Hope this works now. Please report so we can close this issue.

**Comment by regulskimichal** [comment]
I created pull request. You can test it on your own. Manjaro x64
![image](https://user-images.githubusercontent.com/3966163/44733149-3f3e1280-aae7-11e8-8d69-3a2ce764fae5.png)
![image](https://user-images.githubusercontent.com/3966163/44733188-53820f80-aae7-11e8-9043-527a052a9d7a.png)

**Comment by kirbyfan64** [comment]
I can confirm it all works. Thanks!!
