### ISSUE TITLE
Quick Reply section is bugged

### ISSUE THREAD

**Issue by agottschling** [LightSnowDev/Material-Spring#6]
Hey all, 
I've been using the theme for a while now, and really like it (it works really well on macOS btw). But there's one problem that makes it almost impossible to use. 
![screen shot 2018-09-27 at 1 21 35 pm](https://user-images.githubusercontent.com/8459640/46163430-3a40c000-c259-11e8-9f01-6f1755a6fea1.png)

As you can see, Open tracking is on, but link tracking is off. However, it's impossible to tell the two apart without hovering over the icon and reading the tooltip. Also, the Send button is totally white, and I couldn't tell what it was at first. 
Is this something that I'm doing wrong, or is this a bug in the theme?
Let me know if there's anything I can do to help. 

System Info: macOS 10.14 Mojave, Mailspring 1.4.2

**Comment by LightSnowDev** [comment]
I'm on it. Should be fixed soon.

**Comment by agottschling** [comment]
Any update on this?

**Comment by LightSnowDev** [comment]
I replaced the last 2 images but the chevron clips away. Maybe I will just hide the chevron, since its now more obvious to click the button to change its state.
![image](https://user-images.githubusercontent.com/10366675/46430999-ee0ae980-c74a-11e8-9ff8-c19a5e4dbf11.png)

**Comment by LightSnowDev** [comment]
I pushed a new version. Check out, if it fits with linux as well.
![image](https://user-images.githubusercontent.com/10366675/46923190-9145e380-d014-11e8-91cc-5e26fbe9cd77.png)
I will look into that send icon later this week.

Edit: damn, that date icon is too small. But nevertheless, the chevrons survived.

**Comment by regulskimichal** [comment]
Yes, it works. But there is another problem with icons. On my Linux they scales wrong. I don't know why, before it was ok.
![image](https://user-images.githubusercontent.com/3966163/47015887-868f6980-d14e-11e8-95dc-958884cd88b5.png)

**Comment by LightSnowDev** [comment]
The newest commit tries to fix this problem. Please test it. It works for me with 100% and 125%.

**Comment by LightSnowDev** [comment]
Closing this issue, since it should be fixed.
